### ISSUE TITLE
Crash when trying to display

### ISSUE THREAD

**Issue by aleixpol** [maliit/keyboard#97]
I'm reproduceably seeing this crash in KDE Neon. This keeps the keyboard from ever showing.

```
#0  QList<QtWaylandClient::QWaylandDisplay::RegistryGlobal>::const_iterator::operator* (this=<synthetic pointer>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:313

warning: Source file is more recent than executable.
313             inline const T &operator*() const { return i->t(); }
[Current thread is 1 (Thread 0x7f46e84f3940 (LWP 2065))]
(gdb) where
#0  QList<QtWaylandClient::QWaylandDisplay::RegistryGlobal>::const_iterator::operator*() const (this=<synthetic pointer>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:313
#1  QtWaylandClient::QWaylandInputPanelShellIntegration::initialize(QtWaylandClient::QWaylandDisplay*) (this=0x55a64678a460, display=0x55a64628f900) at ./src/qt/plugins/shellintegration/qwaylandinputpanelshellintegration.cpp:35
#2  0x00007f46e7e9f8a8 in QtWaylandClient::QWaylandShellIntegrationFactory::create(QString const&, QtWaylandClient::QWaylandDisplay*, QStringList const&, QString const&) () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#3  0x00007f46e7e6d981 in QtWaylandClient::QWaylandIntegration::createShellIntegration(QString const&) () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#4  0x00007f46e7e6dc9b in QtWaylandClient::QWaylandIntegration::initializeShellIntegration() () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#5  0x00007f46e7e6e6ad in QtWaylandClient::QWaylandIntegration::shellIntegration() const () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#6  0x00007f46e7e80f81 in QtWaylandClient::QWaylandWindow::shouldCreateShellSurface() const () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#7  0x00007f46e7e8aeca in QtWaylandClient::QWaylandWindow::initWindow() () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#8  0x00007f46e7e8b68e in QtWaylandClient::QWaylandWindow::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#9  0x00007f46ec4ef9eb in QWindowPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007f46ec1291be in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f46ed9c2500 in Maliit::Wayland::InputMethodContext::InputMethodContext(MInputContextConnection*, zwp_input_method_context_v1*) () at /lib/x86_64-linux-gnu/libmaliit-plugins.so.2
#12 0x00007f46ed9c2807 in Maliit::Wayland::InputMethod::zwp_input_method_v1_activate(zwp_input_method_context_v1*) () at /lib/x86_64-linux-gnu/libmaliit-plugins.so.2
#13 0x00007f46eb4e5ff5 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#14 0x00007f46eb4e540a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#15 0x00007f46eb81e3a8 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#16 0x00007f46eb81ac48 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#17 0x00007f46eb81c21c in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#18 0x00007f46e7e7a12a in QtWaylandClient::QWaylandDisplay::flushRequests() () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#19 0x00007f46ec1291f0 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f46ec14ca2c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f46ec0f0c9b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f46ec0f8e44 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x000055a644fe404c in main(int, char**) (argc=<optimized out>, argv=0x7ffcba4eb378) at ./src/keyboard/keyboard.cpp:40
(gdb) frame 1
#1  QtWaylandClient::QWaylandInputPanelShellIntegration::initialize (this=0x55a64678a460, display=0x55a64628f900) at ./src/qt/plugins/shellintegration/qwaylandinputpanelshellintegration.cpp:35
35      ./src/qt/plugins/shellintegration/qwaylandinputpanelshellintegration.cpp: No such file or directory.
(gdb) p display
$1 = (QtWaylandClient::QWaylandDisplay *) 0x55a64628f900
(gdb) p globals
$2 = {<QListSpecialMethods<QtWaylandClient::QWaylandDisplay::RegistryGlobal>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
                _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55a64630b4f0}, d = 0x55a64630b4f0}}
(gdb) p globals.count()
Cannot evaluate function -- may be inlined

```

**Comment by dobey** [comment]
This seems like maybe the same crash as https://github.com/maliit/framework/issues/86 ?

**Comment by aleixpol** [comment]
Yes, closing in favour of that one.
